**Name: Mohammed Varaliya**

**Roll No: T109**

## Rescaling a feature

In [1]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data = np.array([
                [1.0, 2.0],
                [2.0, 3.0],
                [3.0, 4.0]])

scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(data)

print("Original Data:")
print(data)
print("\nMin-Max Scaled Data:")
print(scaled_data)

Original Data:
[[1. 2.]
 [2. 3.]
 [3. 4.]]

Min-Max Scaled Data:
[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


## Standardizing a Feature

In [4]:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0]])
scaler = StandardScaler()
standardized_data = scaler.fit_transform(data)

print("Original Data:")
print(data)
print("\nStandardized Data:")
print(standardized_data)
print("mean = ", standardized_data.mean())
print("Standard Deviation = ", standardized_data.std())


Original Data:
[[1. 2.]
 [2. 3.]
 [3. 4.]]

Standardized Data:
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
mean =  0.0
Standard Deviation =  0.9999999999999999


## Normalizing Observations

In [5]:
from sklearn.preprocessing import Normalizer
import numpy as np

data = np.array([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0]])
normalizer = Normalizer(norm='l2')
normalized_data = normalizer.fit_transform(data)

print("Original Data:")
print(data)
print("\nNormalized Data:")
print(normalized_data)

Original Data:
[[1. 2.]
 [2. 3.]
 [3. 4.]]

Normalized Data:
[[0.4472136  0.89442719]
 [0.5547002  0.83205029]
 [0.6        0.8       ]]


In [6]:
# transform feature matrix
features_l1_norm =	Normalizer(norm="l1").transform(data)
print("Sum of the first observation's values: {}".format(features_l1_norm[0,0] + features_l1_norm[0, 1]))

Sum of the first observation's values: 1.0


In [7]:
# Display the L1 normalized feature matrix
print("\nL1 Normalized Feature Matrix:")
print(features_l1_norm)


L1 Normalized Feature Matrix:
[[0.33333333 0.66666667]
 [0.4        0.6       ]
 [0.42857143 0.57142857]]
