<h1>Linear Algebra Practical-2</h1>

<h2>1. Addition, subtraction and mutiplication of Two Matrix</h2>

In [1]:
import numpy as np

# Addition, subtraction and mutiplication of Two Matrix
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print("The Matrix a is :")
print(a)
print("The Matrix b is :")
print(b)

print("Addition of two matrix a and b is : ")
print(a+b)

print("Subtraction of two matrix a and b is : ")
print(a-b)

print("Multiplication of two matrix a and b is : ")
print(a*b)

The Matrix a is :
[[1 2]
 [3 4]]
The Matrix b is :
[[5 6]
 [7 8]]
Addition of two matrix a and b is : 
[[ 6  8]
 [10 12]]
Subtraction of two matrix a and b is : 
[[-4 -4]
 [-4 -4]]
Multiplication of two matrix a and b is : 
[[ 5 12]
 [21 32]]


<h2>2. Check if matrix is invertible.</h2>

In [3]:
import numpy as np

matrix = np.array([[5,7], [2,3]])

print("Matrix M = ")
print(matrix)

c = np.linalg.det(matrix)
print("Determinant = ", c)

if(c != 0):
    i = np.linalg.inv(matrix)
    print("Inverse of Matrix M = ")
    print(i)
else:
    print("Matrix M is invertible")

Matrix M = 
[[5 7]
 [2 3]]
Determinant =  0.9999999999999987
Inverse of Matrix M = 
[[ 3. -7.]
 [-2.  5.]]
